<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Diagnostics\" />
    <Folder Include="Correlations\" />
    <Folder Include="Causations\" />
    <Folder Include="Sessions\" />
    <Folder Include="Trace\" />
    <Folder Include="Sinks\" />
    <Folder Include="Cdc\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
  </ItemGroup>

</Project>
